language: php
php:
  - 7.2.15
env:
  - MYSQL_HOST=127.0.0.1 MYSQL_USER=root
services:
  - mysql
addons:
  apt:
    sources:
      #- mysql-5.7-trusty
    packages:
      #- mysql-server
dist: trusty
sudo: required

notifications:
  email: false
before_install:
  - composer self-update --rollback
  #- mysql -e 'CREATE DATABASE moodle;'
  #- mysql -u root --password='' moodle < dbDump/dump.sql
  #- mysql -e 'USE moodle; SELECT * FROM mdl_assignfeedback_customfeedback WHERE id=2;'
install:
  - composer require satooshi/php-coveralls:~0.6@stable
  - composer require --dev phpunit/phpunit ^8
  - composer install
before_script:
  - mkdir -p ./test_reports/logs
script:
  - phpunit --version
  - composer dump-autoload
  - phpunit  --coverage-clover ./test_reports/logs/clover.xml
  - ./phpunit --bootstrap vendor/autoload.php unitTests
after_script:
- php vendor/bin/coveralls -v

after_success:
- coveralls-upload
